# Generated by Django 3.1.3 on 2023-06-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230607_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course',
            new_name='lesson',
        ),
    ]
